# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: marcoshplace
description: > # this means to ignore newlines until "baseurl:"
  A place to store my thoughts and ideas about programming and related stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://marcosh.github.com" # the base hostname & protocol for your site
twitter_username: marcoshuttle
github_username: marcosh

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax

# My settings
categories: [presentations]